name = "MicroUI"
uuid = "8c0ede0a-6911-4ca7-83c4-4fa2fa689698"
authors = ["Mattdef"]
version = "1.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"

[compat]
BenchmarkTools = "1.6.0"
GLFW = "3.4.4"
ModernGL = "1.1.8"
julia = "1.9"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
