name = "MicroUI"
uuid = "8c0ede0a-6911-4ca7-83c4-4fa2fa689698"
authors = ["Mattdef"]
version = "0.1.1"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
